# Generated by Django 6.0.4 on 2026-08-01 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_merge_0007_userprofile_is_onboarded_0008_chat_logs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='otp',
        ),
        migrations.RemoveField(
            model_name='user',
            name='otp_created_at',
        ),
    ]
