# Generated by Django 6.0.5 on 2026-08-18 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_affiliateorder_id_alter_cart_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal_logs',
            name='ai_insights',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='meal_logs',
            name='carbs_gm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='meal_logs',
            name='detected_items',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='meal_logs',
            name='fat_gm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='meal_logs',
            name='meal_photo_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='meal_logs',
            name='protein_gm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
    ]
