# Generated by Django 6.1 on 2026-08-21 17:16

import pgvector.django.vector
import uuid
from django.db import migrations, models


from pgvector.django import VectorExtension


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_meal_logs_ai_insights_alter_meal_logs_carbs_gm_and_more'),
    ]

    operations = [
        VectorExtension(),
        migrations.CreateModel(
            name='RagDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dataset_type', models.CharField(max_length=50)),
                ('source_name', models.CharField(max_length=255)),
                ('page_number', models.IntegerField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('content', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=768, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
