# Generated by Django 6.0.5 on 2026-08-20 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_meal_logs_ai_insights_alter_meal_logs_carbs_gm_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal_logs',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
